// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolyqMEWZyJKfjsu2ZX5k60LejKiEAn9U',
    appId: '1:680565328402:web:76c0d9904f0705b18066cb',
    messagingSenderId: '680565328402',
    projectId: 'fatma-48657',
    authDomain: 'fatma-48657.firebaseapp.com',
    storageBucket: 'fatma-48657.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT6UbrZjHgQ4cZOtKg7VO3H5d5vaFAlA4',
    appId: '1:680565328402:android:2a2b73eabbfe1eba8066cb',
    messagingSenderId: '680565328402',
    projectId: 'fatma-48657',
    storageBucket: 'fatma-48657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu_m46-4tfxzKNUGd75lNb3_4rZUnwHC4',
    appId: '1:680565328402:ios:393c49e8b2c5dbc98066cb',
    messagingSenderId: '680565328402',
    projectId: 'fatma-48657',
    storageBucket: 'fatma-48657.appspot.com',
    iosBundleId: 'com.example.istegramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu_m46-4tfxzKNUGd75lNb3_4rZUnwHC4',
    appId: '1:680565328402:ios:393c49e8b2c5dbc98066cb',
    messagingSenderId: '680565328402',
    projectId: 'fatma-48657',
    storageBucket: 'fatma-48657.appspot.com',
    iosBundleId: 'com.example.istegramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBolyqMEWZyJKfjsu2ZX5k60LejKiEAn9U',
    appId: '1:680565328402:web:a1ecdfed46efc6b28066cb',
    messagingSenderId: '680565328402',
    projectId: 'fatma-48657',
    authDomain: 'fatma-48657.firebaseapp.com',
    storageBucket: 'fatma-48657.appspot.com',
  );
}
